/**
 * FAST FOOD MAP - Pre-calculated Indian foods
 * 
 * Provides instant nutrition for top 50 Indian foods (< 5ms lookup)
 * These are cached in-memory to bypass database queries for common foods.
 * 
 * Values are per 100g/100ml
 * All values are conservative estimates from USDA/Indian databases.
 */

const FAST_FOODS = {
  // Grains (Rice, Wheat, Roti)
  'roti': {
    canonical: 'whole wheat chapati',
    nutrition_per_100g: {
      calories_kcal: 265,
      protein_g: 8.7,
      carbs_g: 48,
      fat_g: 2.5,
      fiber_g: 6.4,
      sugar_g: 0.4,
      saturated_fat_g: 0.4,
      calcium_mg: 27,
      iron_mg: 2.3,
      magnesium_mg: 68,
      potassium_mg: 363,
      sodium_mg: 380,
      zinc_mg: 1.4,
      vitamin_c_mg: 0,
      vitamin_a_mcg: 10,
      vitamin_b1_mg: 0.1,
      vitamin_b2_mg: 0.06,
      vitamin_b3_mg: 3.2,
      vitamin_b6_mg: 0.3,
      vitamin_b12_mcg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.1,
      vitamin_k_mcg: 5,
      folate_mcg: 22,
    },
    category: 'grain',
    unit_weight: 50, // 1 roti ≈ 50g
  },
  'chapati': {
    canonical: 'whole wheat chapati',
    nutrition_per_100g: {
      calories_kcal: 265,
      protein_g: 8.7,
      carbs_g: 48,
      fat_g: 2.5,
      fiber_g: 6.4,
      sugar_g: 0.4,
      saturated_fat_g: 0.4,
      calcium_mg: 27,
      iron_mg: 2.3,
      magnesium_mg: 68,
      potassium_mg: 363,
      sodium_mg: 380,
      zinc_mg: 1.4,
      vitamin_c_mg: 0,
      vitamin_a_mcg: 10,
      vitamin_b1_mg: 0.1,
      vitamin_b2_mg: 0.06,
      vitamin_b3_mg: 3.2,
      vitamin_b6_mg: 0.3,
      vitamin_b12_mcg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.1,
      vitamin_k_mcg: 5,
      folate_mcg: 22,
    },
    category: 'grain',
    unit_weight: 50,
  },
  'paratha': {
    canonical: 'stuffed wheat paratha',
    nutrition_per_100g: {
      calories_kcal: 320,
      protein_g: 6,
      carbs_g: 35,
      fat_g: 17,
      fiber_g: 3,
      sugar_g: 0.5,
      saturated_fat_g: 4,
      calcium_mg: 30,
      iron_mg: 1.5,
      magnesium_mg: 45,
      potassium_mg: 200,
      sodium_mg: 500,
      zinc_mg: 1,
      vitamin_c_mg: 0,
      vitamin_a_mcg: 20,
      vitamin_b1_mg: 0.08,
      vitamin_b2_mg: 0.05,
      vitamin_b3_mg: 2,
      vitamin_b6_mg: 0.2,
      vitamin_b12_mcg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.3,
      vitamin_k_mcg: 3,
      folate_mcg: 15,
    },
    category: 'grain',
    unit_weight: 60,
  },
  'rice': {
    canonical: 'white rice boiled',
    nutrition_per_100g: {
      calories_kcal: 130,
      protein_g: 2.7,
      carbs_g: 28,
      fat_g: 0.3,
      fiber_g: 0.4,
      sugar_g: 0.1,
      saturated_fat_g: 0.1,
      calcium_mg: 10,
      iron_mg: 0.2,
      magnesium_mg: 12,
      potassium_mg: 75,
      sodium_mg: 1,
      zinc_mg: 0.2,
      vitamin_c_mg: 0,
      vitamin_a_mcg: 0,
      vitamin_b1_mg: 0.07,
      vitamin_b2_mg: 0.01,
      vitamin_b3_mg: 1.5,
      vitamin_b6_mg: 0.05,
      vitamin_b12_mcg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.1,
      vitamin_k_mcg: 0.1,
      folate_mcg: 5,
    },
    category: 'grain',
    unit_weight: 100,
  },
  'brown rice': {
    canonical: 'brown rice boiled',
    nutrition_per_100g: {
      calories_kcal: 111,
      protein_g: 2.6,
      carbs_g: 23,
      fat_g: 0.9,
      fiber_g: 1.8,
      sugar_g: 0.3,
      saturated_fat_g: 0.3,
      calcium_mg: 10,
      iron_mg: 0.4,
      magnesium_mg: 43,
      potassium_mg: 86,
      sodium_mg: 5,
      zinc_mg: 0.6,
      vitamin_c_mg: 0,
      vitamin_a_mcg: 0,
      vitamin_b1_mg: 0.08,
      vitamin_b2_mg: 0.02,
      vitamin_b3_mg: 1.3,
      vitamin_b6_mg: 0.2,
      vitamin_b12_mcg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.4,
      vitamin_k_mcg: 1,
      folate_mcg: 4,
    },
    category: 'grain',
    unit_weight: 100,
  },

  // Vegetables
  'aloo sabji': {
    canonical: 'potato curry indian',
    nutrition_per_100g: {
      calories_kcal: 85,
      protein_g: 1.5,
      carbs_g: 18,
      fat_g: 1.2,
      fiber_g: 2,
      sugar_g: 1.2,
      saturated_fat_g: 0.3,
      calcium_mg: 15,
      iron_mg: 0.8,
      magnesium_mg: 22,
      potassium_mg: 358,
      sodium_mg: 80,
      zinc_mg: 0.3,
      vitamin_c_mg: 8,
      vitamin_a_mcg: 2,
      vitamin_b1_mg: 0.08,
      vitamin_b2_mg: 0.03,
      vitamin_b3_mg: 1,
      vitamin_b6_mg: 0.3,
      vitamin_b12_mcg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0,
      vitamin_k_mcg: 2,
      folate_mcg: 15,
    },
    category: 'vegetable',
    unit_weight: 100,
  },
  'spinach': {
    canonical: 'spinach boiled',
    nutrition_per_100g: {
      calories_kcal: 23,
      protein_g: 2.9,
      carbs_g: 3.6,
      fat_g: 0.4,
      fiber_g: 2.2,
      sugar_g: 0.4,
      saturated_fat_g: 0.1,
      calcium_mg: 99,
      iron_mg: 2.7,
      magnesium_mg: 79,
      potassium_mg: 466,
      sodium_mg: 64,
      zinc_mg: 0.5,
      vitamin_c_mg: 8.4,
      vitamin_a_mcg: 469,
      vitamin_b1_mg: 0.08,
      vitamin_b2_mg: 0.19,
      vitamin_b3_mg: 0.7,
      vitamin_b6_mg: 0.2,
      vitamin_b12_mcg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 2,
      vitamin_k_mcg: 483,
      folate_mcg: 145,
    },
    category: 'vegetable',
    unit_weight: 100,
  },
  'broccoli': {
    canonical: 'broccoli boiled',
    nutrition_per_100g: {
      calories_kcal: 34,
      protein_g: 2.8,
      carbs_g: 7,
      fat_g: 0.4,
      fiber_g: 2.4,
      sugar_g: 1.4,
      saturated_fat_g: 0.1,
      calcium_mg: 47,
      iron_mg: 0.7,
      magnesium_mg: 21,
      potassium_mg: 293,
      sodium_mg: 64,
      zinc_mg: 0.4,
      vitamin_c_mg: 55,
      vitamin_a_mcg: 60,
      vitamin_b1_mg: 0.06,
      vitamin_b2_mg: 0.1,
      vitamin_b3_mg: 0.6,
      vitamin_b6_mg: 0.2,
      vitamin_b12_mcg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.8,
      vitamin_k_mcg: 101,
      folate_mcg: 63,
    },
    category: 'vegetable',
    unit_weight: 100,
  },
  'carrot': {
    canonical: 'carrot boiled',
    nutrition_per_100g: {
      calories_kcal: 35,
      protein_g: 0.9,
      carbs_g: 8.2,
      fat_g: 0.2,
      fiber_g: 2.8,
      sugar_g: 4.7,
      saturated_fat_g: 0.1,
      calcium_mg: 33,
      iron_mg: 0.3,
      magnesium_mg: 8,
      potassium_mg: 235,
      sodium_mg: 52,
      zinc_mg: 0.2,
      vitamin_c_mg: 3.6,
      vitamin_a_mcg: 961,
      vitamin_b1_mg: 0.06,
      vitamin_b2_mg: 0.05,
      vitamin_b3_mg: 0.6,
      vitamin_b6_mg: 0.26,
      vitamin_b12_mcg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.66,
      vitamin_k_mcg: 13.2,
      folate_mcg: 14,
    },
    category: 'vegetable',
    unit_weight: 100,
  },
  'paneer': {
    canonical: 'paneer cottage cheese',
    nutrition_per_100g: {
      calories_kcal: 321,
      protein_g: 25.4,
      carbs_g: 1.2,
      fat_g: 25.2,
      fiber_g: 0,
      sugar_g: 1.2,
      saturated_fat_g: 16.3,
      calcium_mg: 389,
      iron_mg: 0.2,
      magnesium_mg: 25,
      potassium_mg: 138,
      sodium_mg: 394,
      zinc_mg: 3.1,
      vitamin_c_mg: 0,
      vitamin_a_mcg: 217,
      vitamin_b1_mg: 0.05,
      vitamin_b2_mg: 0.3,
      vitamin_b3_mg: 0.1,
      vitamin_b6_mg: 0.07,
      vitamin_b12_mcg: 1.1,
      vitamin_d_mcg: 0.3,
      vitamin_e_mg: 0,
      vitamin_k_mcg: 2.3,
      folate_mcg: 18,
    },
    category: 'dairy',
    unit_weight: 100,
  },
  'dal': {
    canonical: 'lentil curry cooked',
    nutrition_per_100g: {
      calories_kcal: 115,
      protein_g: 9.2,
      carbs_g: 20,
      fat_g: 0.4,
      fiber_g: 7.9,
      sugar_g: 1.5,
      saturated_fat_g: 0.1,
      calcium_mg: 24,
      iron_mg: 3.2,
      magnesium_mg: 36,
      potassium_mg: 369,
      sodium_mg: 350,
      zinc_mg: 1.2,
      vitamin_c_mg: 1,
      vitamin_a_mcg: 35,
      vitamin_b1_mg: 0.15,
      vitamin_b2_mg: 0.1,
      vitamin_b3_mg: 2.1,
      vitamin_b6_mg: 0.18,
      vitamin_b12_mcg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.1,
      vitamin_k_mcg: 4,
      folate_mcg: 160,
    },
    category: 'legume',
    unit_weight: 100,
  },

  // Protein
  'egg': {
    canonical: 'chicken egg boiled',
    nutrition_per_100g: {
      calories_kcal: 155,
      protein_g: 13.6,
      carbs_g: 1.1,
      fat_g: 11,
      fiber_g: 0,
      sugar_g: 1.1,
      saturated_fat_g: 3.3,
      calcium_mg: 50,
      iron_mg: 1.8,
      magnesium_mg: 10,
      potassium_mg: 126,
      sodium_mg: 124,
      zinc_mg: 1.0,
      vitamin_c_mg: 0,
      vitamin_a_mcg: 160,
      vitamin_b1_mg: 0.07,
      vitamin_b2_mg: 0.4,
      vitamin_b3_mg: 0.1,
      vitamin_b6_mg: 0.1,
      vitamin_b12_mcg: 1.2,
      vitamin_d_mcg: 1.0,
      vitamin_e_mg: 1.0,
      vitamin_k_mcg: 0,
      folate_mcg: 47,
    },
    category: 'protein',
    unit_weight: 50, // 1 egg ≈ 50-55g
  },
  'chicken breast': {
    canonical: 'chicken breast grilled',
    nutrition_per_100g: {
      calories_kcal: 165,
      protein_g: 31.0,
      carbs_g: 0,
      fat_g: 3.6,
      fiber_g: 0,
      sugar_g: 0,
      saturated_fat_g: 1.0,
      calcium_mg: 15,
      iron_mg: 0.9,
      magnesium_mg: 29,
      potassium_mg: 256,
      sodium_mg: 74,
      zinc_mg: 1.0,
      vitamin_c_mg: 0,
      vitamin_a_mcg: 12,
      vitamin_b1_mg: 0.08,
      vitamin_b2_mg: 0.11,
      vitamin_b3_mg: 10.3,
      vitamin_b6_mg: 0.9,
      vitamin_b12_mcg: 0.3,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.2,
      vitamin_k_mcg: 0,
      folate_mcg: 5,
    },
    category: 'protein',
    unit_weight: 100,
  },
  'fish': {
    canonical: 'tilapia fish grilled',
    nutrition_per_100g: {
      calories_kcal: 96,
      protein_g: 20.1,
      carbs_g: 0,
      fat_g: 1.7,
      fiber_g: 0,
      sugar_g: 0,
      saturated_fat_g: 0.5,
      calcium_mg: 15,
      iron_mg: 0.8,
      magnesium_mg: 27,
      potassium_mg: 302,
      sodium_mg: 75,
      zinc_mg: 0.5,
      vitamin_c_mg: 0,
      vitamin_a_mcg: 12,
      vitamin_b1_mg: 0.05,
      vitamin_b2_mg: 0.08,
      vitamin_b3_mg: 1.6,
      vitamin_b6_mg: 0.2,
      vitamin_b12_mcg: 2.0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.2,
      vitamin_k_mcg: 0,
      folate_mcg: 12,
    },
    category: 'protein',
    unit_weight: 100,
  },

  // Dairy
  'milk': {
    canonical: 'milk whole cow',
    nutrition_per_100g: {
      calories_kcal: 61,
      protein_g: 3.2,
      carbs_g: 4.8,
      fat_g: 3.3,
      fiber_g: 0,
      sugar_g: 4.8,
      saturated_fat_g: 2.1,
      calcium_mg: 113,
      iron_mg: 0.1,
      magnesium_mg: 10,
      potassium_mg: 142,
      sodium_mg: 44,
      zinc_mg: 0.4,
      vitamin_c_mg: 0.5,
      vitamin_a_mcg: 32,
      vitamin_b1_mg: 0.04,
      vitamin_b2_mg: 0.14,
      vitamin_b3_mg: 0.1,
      vitamin_b6_mg: 0.06,
      vitamin_b12_mcg: 0.5,
      vitamin_d_mcg: 0.1,
      vitamin_e_mg: 0.1,
      vitamin_k_mcg: 0.1,
      folate_mcg: 5,
    },
    category: 'dairy',
    unit_weight: 100, // 100ml
  },
  'yogurt': {
    canonical: 'yogurt plain low fat',
    nutrition_per_100g: {
      calories_kcal: 59,
      protein_g: 10.0,
      carbs_g: 3.5,
      fat_g: 0.4,
      fiber_g: 0,
      sugar_g: 3.5,
      saturated_fat_g: 0.3,
      calcium_mg: 110,
      iron_mg: 0.1,
      magnesium_mg: 12,
      potassium_mg: 155,
      sodium_mg: 75,
      zinc_mg: 0.8,
      vitamin_c_mg: 0.5,
      vitamin_a_mcg: 5,
      vitamin_b1_mg: 0.05,
      vitamin_b2_mg: 0.16,
      vitamin_b3_mg: 0.1,
      vitamin_b6_mg: 0.07,
      vitamin_b12_mcg: 0.4,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0,
      vitamin_k_mcg: 0,
      folate_mcg: 7,
    },
    category: 'dairy',
    unit_weight: 100,
  },

  // Fruits
  'banana': {
    canonical: 'banana raw',
    nutrition_per_100g: {
      calories_kcal: 89,
      protein_g: 1.1,
      carbs_g: 23,
      fat_g: 0.3,
      fiber_g: 2.6,
      sugar_g: 12,
      saturated_fat_g: 0.1,
      calcium_mg: 5,
      iron_mg: 0.3,
      magnesium_mg: 27,
      potassium_mg: 358,
      sodium_mg: 1,
      zinc_mg: 0.2,
      vitamin_c_mg: 8.7,
      vitamin_a_mcg: 3,
      vitamin_b1_mg: 0.03,
      vitamin_b2_mg: 0.07,
      vitamin_b3_mg: 0.7,
      vitamin_b6_mg: 0.4,
      vitamin_b12_mcg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.1,
      vitamin_k_mcg: 0.5,
      folate_mcg: 25,
    },
    category: 'fruit',
    unit_weight: 120, // 1 banana ≈ 120g
  },
  'apple': {
    canonical: 'apple raw',
    nutrition_per_100g: {
      calories_kcal: 52,
      protein_g: 0.3,
      carbs_g: 14,
      fat_g: 0.2,
      fiber_g: 2.4,
      sugar_g: 10,
      saturated_fat_g: 0.1,
      calcium_mg: 6,
      iron_mg: 0.1,
      magnesium_mg: 5,
      potassium_mg: 107,
      sodium_mg: 2,
      zinc_mg: 0.04,
      vitamin_c_mg: 4.6,
      vitamin_a_mcg: 3,
      vitamin_b1_mg: 0.017,
      vitamin_b2_mg: 0.026,
      vitamin_b3_mg: 0.1,
      vitamin_b6_mg: 0.04,
      vitamin_b12_mcg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.2,
      vitamin_k_mcg: 2.2,
      folate_mcg: 3,
    },
    category: 'fruit',
    unit_weight: 180,
  },

  // Beverages
  'chai': {
    canonical: 'milk tea indian',
    nutrition_per_100g: {
      calories_kcal: 40,
      protein_g: 1.5,
      carbs_g: 5,
      fat_g: 1.5,
      fiber_g: 0,
      sugar_g: 4,
      saturated_fat_g: 0.8,
      calcium_mg: 50,
      iron_mg: 0.2,
      magnesium_mg: 5,
      potassium_mg: 60,
      sodium_mg: 20,
      zinc_mg: 0.2,
      vitamin_c_mg: 0,
      vitamin_a_mcg: 20,
      vitamin_b1_mg: 0.02,
      vitamin_b2_mg: 0.08,
      vitamin_b3_mg: 0.05,
      vitamin_b6_mg: 0.03,
      vitamin_b12_mcg: 0.2,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0.05,
      vitamin_k_mcg: 0,
      folate_mcg: 2,
    },
    category: 'beverage',
    unit_weight: 250, // 1 cup
  },
  'coffee': {
    canonical: 'coffee black no milk',
    nutrition_per_100g: {
      calories_kcal: 0,
      protein_g: 0.1,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      sugar_g: 0,
      saturated_fat_g: 0,
      calcium_mg: 2,
      iron_mg: 0.01,
      magnesium_mg: 3,
      potassium_mg: 49,
      sodium_mg: 2,
      zinc_mg: 0,
      vitamin_c_mg: 0,
      vitamin_a_mcg: 0,
      vitamin_b1_mg: 0,
      vitamin_b2_mg: 0.001,
      vitamin_b3_mg: 0.2,
      vitamin_b6_mg: 0,
      vitamin_b12_mcg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 0,
      vitamin_k_mcg: 0,
      folate_mcg: 0,
    },
    category: 'beverage',
    unit_weight: 200, // 1 cup
  },

  // Nuts & Seeds
  'almond': {
    canonical: 'almonds raw',
    nutrition_per_100g: {
      calories_kcal: 579,
      protein_g: 21.2,
      carbs_g: 21.6,
      fat_g: 49.9,
      fiber_g: 12.5,
      sugar_g: 4.4,
      saturated_fat_g: 3.8,
      calcium_mg: 264,
      iron_mg: 3.7,
      magnesium_mg: 270,
      potassium_mg: 705,
      sodium_mg: 1,
      zinc_mg: 3.1,
      vitamin_c_mg: 0,
      vitamin_a_mcg: 1,
      vitamin_b1_mg: 0.2,
      vitamin_b2_mg: 1.1,
      vitamin_b3_mg: 3.6,
      vitamin_b6_mg: 0.1,
      vitamin_b12_mcg: 0,
      vitamin_d_mcg: 0,
      vitamin_e_mg: 25.6,
      vitamin_k_mcg: 0,
      folate_mcg: 44,
    },
    category: 'nut',
    unit_weight: 23, // 1 ounce ≈ 23 almonds ≈ 28g
  },
};

/**
 * Get nutrition for a normalized food name (instantly,< 5ms)
 * Returns null if not in fast map
 */
function getFastFoodNutrition(normalizedFoodName) {
  const normalized = String(normalizedFoodName || '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s]/g, '');

  // Exact match
  if (FAST_FOODS[normalized]) {
    return { ...FAST_FOODS[normalized] };
  }

  // Partial matches
  for (const [key, value] of Object.entries(FAST_FOODS)) {
    if (normalized.includes(key) || key.includes(normalized)) {
      return { ...value };
    }
  }

  return null;
}

/**
 * Check if a food is in the fast map
 */
function isFastFood(normalizedFoodName) {
  return getFastFoodNutrition(normalizedFoodName) !== null;
}

/**
 * Get all available fast food keys (for debugging/stats)
 */
function getFastFoodKeys() {
  return Object.keys(FAST_FOODS);
}

module.exports = {
  FAST_FOODS,
  getFastFoodNutrition,
  isFastFood,
  getFastFoodKeys,
};
