/**
 * FIXED NUTRITION PIPELINE - COMPLETE REWRITE
 * 
 * This module handles the complete food search, nutrient transformation, scaling,
 * and aggregation using proper canonical nutrients (nulls for missing data, not zeros).
 * 
 * KEY FIXES:
 * - Uses canonical nutrient schema instead of arbitrary fields
 * - Never defaults missing nutrients to 0 (uses null)
 * - Safely merges database + AI results without overwriting
 * - Scales ALL nutrients including micronutrients
 * - Handles cooking method variants (boiled, fried, grilled, etc.)
 * - Provides confidence/source metadata for each result
 */

const {
  parseFoodInput,
  convertToGrams,
  logNutritionAudit,
} = require("../utils/nutritionEngine");
const {
  mapDbFoodToCanonical,
  mapAiResponseToCanonical,
  safeMergeNutrients,
  scaleNutrientsByWeight,
  aggregateNutrients,
  recalculateCalories,
  formatNutrientForDisplay,
  validateNutrientValues,
  performSanityCheck,
} = require("../utils/nutrientTransformer");
const {
  extractBaseFoodName,
  adjustForCookingMethod,
  createCookingMetadata,
} = require("../utils/cookingMethodHandler");
const { findBestFoodMatch } = require("./foodSearchService");

/**
 * Analyzes one food from database (if available) or uses AI fallback.
 * Returns canonical nutrient object with metadata.
 * 
 * @param {string} foodName - Original user food input
 * @param {Function} analyzeWithAI - Function to call for AI fallback
 * @returns {Object} {nutrition, source, confidence, metadata}
 */
async function analyzeOneFood(foodName, analyzeWithAI) {
  const startTime = Date.now();

  try {
    // Try database first
    const dbMatch = await findBestFoodMatch(foodName);

    if (dbMatch && dbMatch.food) {
      logNutritionAudit("db_food_found", {
        originalInput: foodName,
        matchedFood: dbMatch.food.name,
        cookingMethod: dbMatch.cookingMethod,
      });

      // Convert database food to canonical nutrients
      let nutrition = mapDbFoodToCanonical(dbMatch.food);

      // Apply cooking method adjustments ONLY if matched food is NOT already in that cooked state
      // E.g., don't apply "boiled" adjustment to "Boiled Egg" (already boiled in DB)
      // But DO apply "fried" adjustment to "Chicken Breast" if user asked for fried variant
      const matchedFoodNameLower = dbMatch.food.name.toLowerCase();
      const shouldApplyCookingAdjustment = dbMatch.cookingMethod && 
        dbMatch.cookingMethod !== 'raw' &&
        !matchedFoodNameLower.includes(dbMatch.cookingMethod);
      
      if (shouldApplyCookingAdjustment) {
        nutrition = adjustForCookingMethod(nutrition, dbMatch.cookingMethod, 100);
        
        logNutritionAudit("cooking_adjustment_applied", {
          originalInput: foodName,
          cookingMethod: dbMatch.cookingMethod,
          adjustedNutrition: nutrition,
        });
      }

      // Validate values
      validateNutrientValues(nutrition, dbMatch.food.name);

      // Perform sanity check to catch bad matches
      const sanityCheck = performSanityCheck(foodName, dbMatch.food.name, nutrition);
      let confidence = "high";
      if (!sanityCheck.valid) {
        logNutritionAudit("sanity_check_failed", {
          userInput: foodName,
          matched: dbMatch.food.name,
          issues: sanityCheck.issues,
        });
        confidence = sanityCheck.confidence; // medium or low
      }

      return {
        nutrition,
        source: "database",
        confidence,
        matched_food_name: dbMatch.food.name,
        matched_pattern: dbMatch.matchedPattern,
        cooking_method: dbMatch.cookingMethod || null,
        metadata: createCookingMetadata(
          foodName,
          extractBaseFoodName(foodName),
          dbMatch.cookingMethod,
          dbMatch.food.name
        ),
      };
    }

    // Database miss – use AI fallback
    logNutritionAudit("db_food_not_found", { originalInput: foodName });

    const aiResult = await analyzeWithAI(foodName);
    let aiNutrition = mapAiResponseToCanonical(aiResult);

    // Recalculate calories from macros
    aiNutrition = recalculateCalories(aiNutrition);

    logNutritionAudit("ai_fallback_used", {
      originalInput: foodName,
      aiNutrition,
    });

    return {
      nutrition: aiNutrition,
      source: "ai_fallback",
      confidence: "medium",
      matched_food_name: foodName,
      matched_pattern: "ai_generated",
      cooking_method: null,
      metadata: {
        user_input: foodName,
        note: "Generated by AI (not in database)",
      },
    };
  } catch (error) {
    logNutritionAudit("food_analysis_error", {
      originalInput: foodName,
      error: error.message,
    });
    throw error;
  }
}

/**
 * Scales nutrient by weight but handles cooking piece conversions properly.
 * If user says "2 eggs", calculates 2 * 50g (piece weight) = 100g total.
 */
function getWeightInGrams(quantity, unit, foodName) {
  try {
    return convertToGrams(quantity, unit, foodName);
  } catch (err) {
    logNutritionAudit('weight_conversion_fallback', { foodName, quantity, unit, error: err.message });
    // Default: treat as grams
    return quantity * (unit === 'piece' ? 100 : 1);
  }
}

/**
 * Analyzes complete meal with multiple food items.
 * Handles proper aggregation and metadata tracking.
 */
async function analyzeMealComplete(foodInput, analyzeWithAI) {
  try {
    // Parse input
    const foodItems = parseFoodInput(foodInput);
    if (foodItems.length === 0) {
      throw new Error("Could not extract any food items from input");
    }

    logNutritionAudit("meal_parsing_complete", {
      input: foodInput,
      itemCount: foodItems.length,
      items: foodItems.map(i => ({ food_name: i.food_name, quantity: i.quantity, unit: i.unit })),
    });

    // Analyze each food item
    const analyzedItems = [];
    for (const item of foodItems) {
      const result = await analyzeOneFood(item.food_name, analyzeWithAI);
      
      // Get weight in grams
      const weightInGrams = getWeightInGrams(item.quantity, item.unit, item.food_name);

      // Scale nutrients by weight
      const scaledNutrition = scaleNutrientsByWeight(result.nutrition, weightInGrams);

      logNutritionAudit("item_scaled", {
        food: item.food_name,
        quantity: item.quantity,
        unit: item.unit,
        weightInGrams,
        scaledNutrition,
      });

      analyzedItems.push({
        original_input: item.food_name,
        quantity: item.quantity,
        unit: item.unit,
        weight_grams: weightInGrams,
        nutrition_per_100g: result.nutrition,
        nutrition_scaled: scaledNutrition,
        source: result.source,
        confidence: result.confidence,
        matched_food_name: result.matched_food_name,
        cooking_method: result.cooking_method,
        metadata: result.metadata,
      });
    }

    // Aggregate all nutrients
    const scaledNutrients = analyzedItems.map(item => item.nutrition_scaled);
    const aggregatedNutrition = aggregateNutrients(scaledNutrients);

    // Recalculate calories from aggregated macros
    recalculateCalories(aggregatedNutrition);

    logNutritionAudit("meal_aggregated", {
      input: foodInput,
      itemCount: analyzedItems.length,
      aggregatedNutrition,
    });

    // Determine overall source
    const allFromDb = analyzedItems.every(i => i.source === "database");
    const overallSource = allFromDb ? "database" : "mixed";
    const overallConfidence = allFromDb ? "high" : "medium";

    // Format for API response
    const formatted = formatNutrientForDisplay(aggregatedNutrition);

    return {
      input: foodInput,
      source: overallSource,
      confidence: overallConfidence,
      items: analyzedItems,
      totals: {
        macros: formatted.macros,
        minerals: formatted.minerals,
        vitamins: formatted.vitamins,
      },
      raw_aggregated: aggregatedNutrition, // Keep raw canonical form
    };
  } catch (error) {
    console.error("Error in analyzeMealComplete:", error);
    logNutritionAudit("meal_analysis_error", {
      input: foodInput,
      error: error.message,
    });
    throw error;
  }
}

module.exports = {
  findBestFoodMatch,
  analyzeOneFood,
  analyzeMealComplete,
  getWeightInGrams,
};
